### ISSUE TITLE
在执行GIFDownload.py的时候出现了错误

### ISSUE THREAD

**Issue by bcYwpK3** [OrsPced/PixivRankDownload#1]
c:\>python GIFDownload.py
正在登陆
登录完成
开始下载
Traceback (most recent call last):
  File ".\GIFDownload.py", line 131, in <module>
    test.download(74455834)
  File ".\GIFDownload.py", line 92, in download
    delay = [item["delay"] for item in gif_info["body"]["frames"]]
TypeError: list indices must be integers or slices, not str

**Comment by Velvetalon** [comment]
由于P站登录验证流程更新，此项目目前不可用。
正在正在对代码进行更新已匹配新的流程

**Comment by Velvetalon** [comment]
项目已更新，现在可以正常使用了。
